version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'typescript*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'impact/no-changelog-required'
      - 'github_actions'
      - 'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/templates/github'
    schedule:
      interval: 'daily'
    labels:
      - 'impact/no-changelog-required'
      - 'github_actions'
      - 'dependencies'
      - 'templates/service'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
