name: Testing

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'

jobs:
  test-npm-new-project:
    name:
      Create a new project with npm, install dependencies and run tests/build
    runs-on: ubuntu-latest

    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: 0

    steps:
      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: yarn create bjerk-typescript new-project

      - run: yarn install
        working-directory: new-project

      - run: yarn add fastify
        working-directory: new-project

      - run: yarn test
        working-directory: new-project

      - run: yarn build
        working-directory: new-project

      - run: ls new-project

  test-cmd:
    name: Test the CLI, create new project and run tests/build
    runs-on: ubuntu-latest

    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: 0

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          path: create-bjerk-typescript

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: yarn install
        working-directory: create-bjerk-typescript

      - run:
          node create-bjerk-typescript/cmd/create-bjerk-typescript new-project

      - run: yarn add fastify
        working-directory: new-project

      - run: yarn test
        working-directory: new-project

      - run: yarn build
        working-directory: new-project

      - run: ls new-project
