name: Weekly Cron Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * MON' # Weekly on monday at 12

jobs:
  update-yarn:
    name: Update yarn to latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - run: yarn set version latest

      - run: rm templates/yarn-releases/*

      - run: cp .yarnrc.yml templates/yarnrc.yml

      - run: cp .yarn/releases/* templates/yarn-releases

      - run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      # Run prettier directly, to ensure CHANGELOG is not fixed.
      - run: yarn prettier --write .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(deps): upgrade yarn to latest version'
          author: Bjerk Bot <bjerk-bot@users.noreply.github.com>
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          branch: update-yarn
          team-reviewers: thebranches
          delete-branch: true
          title: 'chore(deps): upgrade yarn to latest version'
          body: |
            This pull request updates Yarn to latest version.

            See the full changelog here:
            https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md

  copy-workflows:
    name: Copy workflows to templates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: cp .github/workflows/pull-request.yml templates/github/workflows/
      - run: cp .github/workflows/workflow.yml templates/github/workflows/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(deps): update github actions workflows'
          author: Bjerk Bot <bjerk-bot@users.noreply.github.com>
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          branch: update-yarn
          team-reviewers: thebranches
          delete-branch: true
          title: 'chore(deps): update github actions workflows'
          body: |
            This pull request updates workflows from main .github directory.

            Reason for this update is probably because Dependabot has updated
            either pull-request.yml or workflow.yml. We synchronize these files
            from the main .github directory to template directory to keep them
            up-to-date.
